version: '3.9'

services:
  nginx:
    container_name: nginx-lab
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - jenkins
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=$NGINX_HOST
      - NGINX_PORT=$NGINX_PORT
    links:
      - "jenkins"
    networks:
      - jenkins
  jenkins:
    container_name: jenkins-lab
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
networks:
  jenkins: {}
volumes:
  jenkins-log: {}
  jenkins-data: {}
