version: '3.9'

services:
  nginx:
    container_name: nginx-lab
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - jenkins
    ports:
      - "80:80"
    networks:
      - jenkins
    volumes:
      - ./nginx/files/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/files/conf.d/:/etc/nginx/conf.d/:z
  jenkins:
    container_name: jenkins-lab
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
networks:
  jenkins: {}
volumes:
  jenkins-log: {}
  jenkins-data: {}
